#!/usr/bin/env node
/**
 * Registry coverage report.
 *
 * Scans registry/ and ercs/ and produces a per-entity matrix of:
 *   - calldata descriptor count
 *   - eip712 descriptor count
 *   - whether a permit-shaped eip712 descriptor exists
 *   - test files vs descriptors (test coverage ratio)
 *   - chain IDs referenced across descriptors
 *   - schema versions in use (v1 / v2)
 *
 * Usage:
 *   node tools/scripts/coverage-report.js               # markdown to stdout
 *   node tools/scripts/coverage-report.js --json        # JSON to stdout
 *   node tools/scripts/coverage-report.js --out FILE    # write markdown to FILE
 *
 * Also appends to $GITHUB_STEP_SUMMARY when set (no-op otherwise).
 *
 * Pure Node stdlib — no extra deps.
 */

const fs = require("fs");
const path = require("path");

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const REGISTRY_DIR = path.join(REPO_ROOT, "registry");
const ERCS_DIR = path.join(REPO_ROOT, "ercs");

const PERMIT_HINTS = [
  "permit",
  "permitsingle",
  "permitbatch",
  "permittransferfrom",
  "permitwitnesstransferfrom",
];

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

function listDescriptors(dir, prefix) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.startsWith(`${prefix}-`) && f.endsWith(".json"))
    .map((f) => path.join(dir, f));
}

function listTests(dir) {
  const testsDir = path.join(dir, "tests");
  if (!fs.existsSync(testsDir)) return [];
  return fs
    .readdirSync(testsDir)
    .filter((f) => f.endsWith(".tests.json"))
    .map((f) => path.join(testsDir, f));
}

function detectSchemaVersion(json) {
  const ref = json && json.$schema;
  if (typeof ref !== "string") return "unknown";
  if (ref.includes("erc7730-v2.schema.json")) return "v2";
  if (ref.includes("erc7730-v1.schema.json")) return "v1";
  return "other";
}

function collectChainIds(json) {
  const chains = new Set();
  const deployments =
    (json && json.context && json.context.contract && json.context.contract.deployments) ||
    (json && json.context && json.context.eip712 && json.context.eip712.deployments) ||
    [];
  for (const d of deployments) {
    if (d && typeof d.chainId === "number") chains.add(d.chainId);
  }
  return chains;
}

function looksLikePermit(filePath, json) {
  const base = path.basename(filePath).toLowerCase();
  if (PERMIT_HINTS.some((h) => base.includes(h))) return true;
  // Look inside display.formats keys for permit-shaped signatures.
  const formats = json && json.display && json.display.formats;
  if (formats && typeof formats === "object") {
    for (const key of Object.keys(formats)) {
      const lk = key.toLowerCase();
      if (lk.startsWith("permit") || lk.includes(" permit(")) return true;
    }
  }
  return false;
}

function analyzeEntity(entityDir) {
  const calldataFiles = listDescriptors(entityDir, "calldata");
  const eip712Files = listDescriptors(entityDir, "eip712");
  const testFiles = listTests(entityDir);

  const chainIds = new Set();
  const schemaVersions = new Set();
  let hasPermit = false;

  for (const f of [...calldataFiles, ...eip712Files]) {
    const json = readJson(f);
    if (!json) continue;
    for (const c of collectChainIds(json)) chainIds.add(c);
    schemaVersions.add(detectSchemaVersion(json));
    if (!hasPermit && looksLikePermit(f, json)) hasPermit = true;
  }

  const descriptorCount = calldataFiles.length + eip712Files.length;
  const testCoverage =
    descriptorCount === 0 ? null : Math.min(testFiles.length / descriptorCount, 1);

  return {
    entity: path.basename(entityDir),
    calldata: calldataFiles.length,
    eip712: eip712Files.length,
    permit: hasPermit,
    tests: testFiles.length,
    testCoverage,
    chains: [...chainIds].sort((a, b) => a - b),
    schemas: [...schemaVersions].sort(),
  };
}

function listEntities(registryDir) {
  if (!fs.existsSync(registryDir)) return [];
  return fs
    .readdirSync(registryDir)
    .map((name) => path.join(registryDir, name))
    .filter((p) => fs.statSync(p).isDirectory())
    .sort();
}

function pct(n) {
  if (n === null) return "—";
  return `${Math.round(n * 100)}%`;
}

function renderMarkdown(rows, ercsStats) {
  const totals = rows.reduce(
    (acc, r) => {
      acc.calldata += r.calldata;
      acc.eip712 += r.eip712;
      acc.tests += r.tests;
      acc.permit += r.permit ? 1 : 0;
      return acc;
    },
    { calldata: 0, eip712: 0, tests: 0, permit: 0 }
  );

  const lines = [];
  lines.push("# ERC-7730 Registry Coverage");
  lines.push("");
  lines.push(
    `_Auto-generated by \`tools/scripts/coverage-report.js\`. ${rows.length} entities, ` +
      `${totals.calldata} calldata + ${totals.eip712} eip712 descriptors, ` +
      `${totals.tests} test files, ${totals.permit} entities with a permit descriptor._`
  );
  lines.push("");
  lines.push(`Common ERC descriptors: **${ercsStats.calldata} calldata**, **${ercsStats.eip712} eip712** under \`ercs/\`.`);
  lines.push("");
  lines.push("| Entity | calldata | eip712 | permit | tests | test cov | chains | schemas |");
  lines.push("| --- | ---: | ---: | :---: | ---: | ---: | --- | --- |");
  for (const r of rows) {
    lines.push(
      `| ${r.entity} | ${r.calldata} | ${r.eip712} | ${r.permit ? "✅" : "—"} | ${r.tests} | ${pct(r.testCoverage)} | ${r.chains.join(", ") || "—"} | ${r.schemas.join(", ") || "—"} |`
    );
  }
  lines.push("");
  lines.push("## Gaps");
  lines.push("");
  const missingTests = rows.filter((r) => r.tests === 0 && r.calldata + r.eip712 > 0);
  const missingPermit = rows.filter((r) => r.calldata > 0 && !r.permit);
  const onV1 = rows.filter((r) => r.schemas.includes("v1"));

  lines.push(`- **${missingTests.length} entities with descriptors but no tests/**: ${missingTests.map((r) => r.entity).join(", ") || "none"}`);
  lines.push(`- **${missingPermit.length} entities with calldata but no permit descriptor**: ${missingPermit.map((r) => r.entity).join(", ") || "none"}`);
  lines.push(`- **${onV1.length} entities still referencing the v1 schema**: ${onV1.map((r) => r.entity).join(", ") || "none"}`);
  lines.push("");
  return lines.join("\n");
}

function appendStepSummary(md) {
  const target = process.env.GITHUB_STEP_SUMMARY;
  if (!target) return;
  try {
    fs.appendFileSync(target, md + "\n");
  } catch (e) {
    console.error(`Failed to write GITHUB_STEP_SUMMARY: ${e.message}`);
  }
}

function main() {
  const args = process.argv.slice(2);
  const wantJson = args.includes("--json");
  const outIdx = args.indexOf("--out");
  const outFile = outIdx >= 0 ? args[outIdx + 1] : null;

  const rows = listEntities(REGISTRY_DIR).map(analyzeEntity);
  const ercsStats = {
    calldata: listDescriptors(ERCS_DIR, "calldata").length,
    eip712: listDescriptors(ERCS_DIR, "eip712").length,
  };

  if (wantJson) {
    const payload = { rows, ercs: ercsStats };
    const out = JSON.stringify(payload, null, 2);
    if (outFile) fs.writeFileSync(outFile, out);
    else process.stdout.write(out + "\n");
    return;
  }

  const md = renderMarkdown(rows, ercsStats);
  if (outFile) fs.writeFileSync(outFile, md);
  else process.stdout.write(md + "\n");
  appendStepSummary(md);
}

main();
