name: ✨ master

on:
  push:
    branches:
      - master
      - demo
    paths-ignore:
      - "developer-preview/**"

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#env:
#  ETHERSCAN_API_HOST: <set this secret to define a custom Etherscan API host>
#  ETHERSCAN_API_KEY: <set this secret to inject Etherscan API key>

jobs:
  validate_descriptors:
    name: 🔎 validate descriptors
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        timeout-minutes: 10
        uses: actions/checkout@v6

      - name: Setup python
        timeout-minutes: 10
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install ERC-7730 library
        timeout-minutes: 10
        run: pip install erc7730

      - name: Validate ERC-7730 descriptors
        timeout-minutes: 10
        run: erc7730 lint registry --gha

  # TODO: To be removed once the registry ownership is transferred
  update_cal:
    name: 🔁 trigger updates
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Trigger update on LedgerHQ/crypto-assets
        if: ${{ !cancelled() }}
        timeout-minutes: 60
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
          repository: LedgerHQ/crypto-assets
          event-type: submodules

      - name: Trigger update on LedgerHQ/python-erc7730
        if: ${{ !cancelled() }}
        timeout-minutes: 60
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
          repository: LedgerHQ/python-erc7730
          event-type: submodules
