name: 🏷️ pull request labels

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup_pull_request:
    name: 🤖 setup pull request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        timeout-minutes: 10
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Add labels
        timeout-minutes: 5
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6
        with:
          sync-labels: true

      - name: Enforce labels
        timeout-minutes: 5
        uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5
        with:
          mode: minimum
          count: 1
          labels: |
            documentation
            specifications
            descriptors
            ci
            tools
          add_comment: true
